POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbW1vYSIsImlkIjoiNWZhMDRmZjRkNGU0MDM0YmQ3NDg1MDk0IiwiaWF0IjoxNjA0MzQxNzc2fQ.rzOQhQB2lX6l93hXm-Y-eqe6j4fb3BhKn0DbZcK70nc

{
  "title": "this is a blog", 
  "author": "very good content yes",
  "url": "google.com"
}

